NewspaperManagment/urls.py
from django.contrib import admin
from django.urls import path ,include, re_path
from django.conf import settings
from django.conf.urls.static import static
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('newspaper/', include('newspaper.urls')),
    path('accounts/', include('accounts.urls')),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
    path('blog/', include('blog.urls')),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [
   url(r'^signup/$', views.signup_view, name='Signup'),
   url(r'^login/$', views.login_view, name='login'),
   url(r'^logout/$', views.logout_view, name='logout'),

]

blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns = [
    path('search/', views.search, name='search'),
]

newspaper/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

app_name = 'newspaper'

urlpatterns = [
    path('', view=views.IndexView.as_view(), name='index'),
    path('<int:pk>/', view=views.AuthorDetailedView.as_view(), name='detailed'),
    path('add/', views.article_add, name='add_article'),
    path('widget/', views.widget_employ, name='widget_employ'),
    path('test/', views.test_form_set, name='test_form'),
]

tutorial-project/mysite/mysite/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]


urlpatterns += i18n_patterns(path("admin/", admin.site.urls), path("", include("cms.urls")))

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/models.py
from django.db import models
from django.utils import translation
from django.utils.html import escape, format_html
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


# Create your models here.
class MyUser(AbstractUser):
    roles = (
             ('User', _('User')),
             ('Author', _('Author')),
    )

    id = models.AutoField(primary_key=True)
    first_name = models.CharField(verbose_name=_('first name'), max_length=200, blank=True)
    last_name = models.CharField(verbose_name=_('last_name'), max_length=200, blank=True)
    username = models.CharField(verbose_name=_('username'), max_length=150, unique=True)
    password = models.CharField(verbose_name=_('password'), max_length=150)
    email = models.EmailField(verbose_name=_('email'), blank=True)
    is_active = models.BooleanField(verbose_name=_('is_active'), default=True)
    is_staff = models.BooleanField(verbose_name=_('is_staff'))
    register_as = models.CharField(verbose_name=_('register_as'), max_length=200, choices=roles)
    REQUIRED_FIELDS = ['register_as']


class OurUser(MyUser):
    class Meta:
        verbose_name = _('our user')
        verbose_name_plural = _('our users')


class Author(MyUser):
    position = models.CharField(verbose_name=_('position'), max_length=200, blank=True)
    position_en = models.CharField(max_length=200, blank=True)
    position_ar = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name = _('author')
        verbose_name_plural = _('authors')

    def __str__(self):
        return self.first_name + self.last_name

    @property
    def get_position(self):
        if translation.get_language() == 'ar':
            self.position = self.position_ar
        else:
            self.position_en = self.position_en
        return self.position


class Article(models.Model):
    category_choices = (
        ('sport', _('sport')),
        ('history', _('history')),
        ('tourism', _('tourism')),
      )

    author = models.ForeignKey(Author, verbose_name=_('author'),  on_delete=models.CASCADE)
    title = models.CharField(verbose_name=_('title'), max_length=200)
    published_date = models.DateTimeField(verbose_name=_('published_date'), auto_now=True)
    category = models.CharField(verbose_name=_('category'), max_length=10, choices=category_choices)
    body = models.TextField(verbose_name=_('body'), default='')
    is_published = models.BooleanField(verbose_name=_('is_published'), default=False)
    description = models.CharField(verbose_name=_('description'), max_length=200, null=True)

    class Meta:
        verbose_name = _('article')
        verbose_name_plural = _('articles')
        permissions = (("mark_published", "set article as published"),)

    def __str__(self):
        return self.title


class ArticleImages(models.Model):
    image = models.ImageField(verbose_name=_('image'),)
    article = models.ForeignKey(Article, verbose_name=_('article'), on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('articles image')
        verbose_name_plural = _('articles images')

    def get_image_element(self):
        return format_html('<img src="%s" />' % escape(self.image.url))

    get_image_element.short_description = 'Image'
    get_image_element.allow_tags = True


class News(models.Model):
    title = models.CharField(verbose_name=_('title'), max_length=255)
    text = models.TextField(verbose_name=_('text'),)

    @property
    def get_title(self):
        if translation.get_language() == 'ar':
            return self.title_ar
        else:
            return self.title_en

newspaper/forms.py
from django.forms import ModelForm
from .models import Article, MyUser
from django.contrib.auth.forms import UserCreationForm


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'author', 'category', 'body']


class UserForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ['first_name', 'last_name', 'username', 'register_as']

newspaper/views.py
from . import forms
from datetime import datetime
from django.views import generic
from .models import Author, MyUser
from django import forms as dj_form
from newspaper.forms import ArticleForm
from django.shortcuts import render, redirect
from django.forms import formset_factory, BaseFormSet
from django.contrib.auth.decorators import login_required


# Create your views here.
class IndexView(generic.ListView):
    model = Author
    template_name = 'newspaper/index.html'
    context_object_name = 'authors'


class AuthorDetailedView(generic.DetailView):
    model = Author
    template_name = 'newspaper/detail.html'


@login_required(login_url='/accounts/login', redirect_field_name='/newspaper/createArticle.html')
def article_add(request):
    username = request.user.username
    the_user = MyUser.objects.get(username=username)

    if the_user.register_as == 'Author':
        if request.method == 'POST':
            form = forms.ArticleForm(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                return redirect("newspaper:index")
        else:
            form = forms.ArticleForm()
            return render(request, 'newspaper/createArticle.html', {'form': form})

    else:
        return redirect("newspaper:index")


class BaseArticleFormSet(BaseFormSet):
    def add_fields(self, form, index):
        super().add_fields(form, index)
        form.fields["my_field"] = dj_form.CharField()


def test_form_set(request):
    ArticleFormSet = formset_factory(ArticleForm, formset=BaseArticleFormSet,
                                     extra=6, max_num=4, validate_max=True,
                                     can_order=True, can_delete=True)
    data = {
        'article-TOTAL_FORMS': '7',
        'article-INITIAL_FORMS': '0',
        'article-MAX_NUM_FORMS': '9',
        'article-0-title': 'Test',
        'article-0-category': 'sport',
        'article-0-author':  Author.objects.get(username='Aya'),
        'article-0-body': 'test 1',
        'article-0-ORDER': '2',
        'article-0-my_field': 'hi',
        'article-1-title': 'Test',
        'article-1-category': 'sport',
        'article-1-author': Author.objects.get(id=request.user.id),
        'article-1-user': 'sport',
        'article-1-body': 'test 2',
        'article-1-ORDER': '0',
        'article-1-my_field': 'hi',
        'article-2-title': 'aaa',
        'article-2-category': 'sport',
        'article-2-author': Author.objects.get(username='Aya'),
        'article-2-pub_date': datetime.now(),
        'article-2-ORDER': '1',
        'article-2-DELETE': 'on',
        'article-2-my_field': 'hi',
    }
    if request.method == 'POST':
        formset = ArticleFormSet(request.POST, request.FILES, prefix='article')
        if formset.is_valid():
            pass
    else:
        formset = ArticleFormSet(data, prefix='article', initial=[
            {
                'title': 'Hi',
                'category': 'sport',
                'author': Author.objects.get(username='fofe'),
                'body': 'test initial 1',
                'ORDER': '2',
            },
            {
                'title': 'Hi',
                'category': 'sport',
                'author': Author.objects.get(username='fofe'),
                'body': 'test initial 2',
                'ORDER': '1',
            },
        ])
        print(formset.is_valid())
        print(formset.initial_form_count())
    return render(request, 'newspaper/forms_set_test.html', {'formset': formset})


def widget_employ(request):
    if request.method == 'POST':
        return redirect("newspaper:index")
    else:
        form = forms.CommentForm()
    return render(request, 'newspaper/image_render_in_admin.html', {'form': form})

newspaper/templates/newspaper/base.html
{% load static i18n %}

<html>

<head>

  {{ form.media }}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous">
</head>

{% block navbar %}
    {% include "newspaper/navigation.html" %}
{% endblock %}

{% block content %}
    {% block content-main %}
    {% endblock %}
{% endblock %}

</html>

newspaper/templates/newspaper/createArticle.html
{% extends "newspaper/base.html" %}
{% load static i18n %}


{% block sub-title %} | Index{% endblock %}

{% block content-main %}

<div>
    <h2> create An article </h2>
    <form action="{% url 'newspaper:add_article' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
</div>

{% endblock %}

newspaper/templates/newspaper/detail.html
{% extends "newspaper/base.html" %}
{% load static i18n %}

{% block sub-title %} | Index{% endblock %}

{% block content-main %}


   <h1> {{ object.first_name }} {{ object.last_name }} </h1>

   {% if error_message %} <p> <strong> {{ error_message }} </strong> </p> {% endif %}

   <form  action="{% url 'newspaper:detailed' object.pk %}" method="post">

       {% csrf_token %}
       {% for article in object.articles_set.all %}
           <label for="choice{{ forloop.counter }}">{{article.title}}</label>
           <br>
           <label for="choice{{ forloop.counter }}">{{article.category}}</label>
           <br>
           <label for="choice{{ forloop.counter }}">{{article.body}}</label>
           <br>
           <p>________________________________________________________________</p>

        <br>
       {% endfor %}

   </form>
{% endblock %}

newspaper/templates/newspaper/forms_set_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {{ formset.management_form }}
        {% csrf_token %}
        <table>
            {% for form in formset %}
            {{ form }}
            {% endfor %}
        </table>
        <button type="submit">submit</button>
    </form>
</body>
</html>

newspaper/templates/newspaper/image_render_in_admin.html
{% load static i18n %}
{% if widget.is_initial %}

<p class="file-upload">

    {{ widget.initial_text }}: <a href="{{ widget.value.url }}">{{ widget.value }}</a>

    {% if not widget.required %}
       <span class="clearable-file-input">
           <input type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}"
              {% if widget.attrs.disabled %}
                  disabled
              {% endif %}>
           <label for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>
       </span>
    {% endif %}
    <br>

     {{ widget.input_text }}:

    {% endif %}
{% if not widget.is_initial %}

  <input id="{{ widget.name }}" type="{{ widget.type }}" name="{{ widget.name }}" onchange="readURL(this)">
{% endif %}

    {% if widget.is_initial %}

{% endif %}

</p>

<script>
function readURL(input_image) {
        if (input_image.files && input_image.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
            var img1 = $("<img>").attr('src', e.target.result)
                                 .width(300)
                                 .height(200);
            $(input_image).after(img1);
            };
            reader.readAsDataURL(input_image.files[0]);
        }
    }
</script>

newspaper/templates/newspaper/index.html
{% extends "newspaper/base.html" %}
{% load static i18n %}
{% block sub-title %} | Index{% endblock %}

{% block content-main %}

    <h1 style="color: deeppink ">
        {% trans " the list of our authors " %}
    </h1>

        {% if authors %}


            <ul>
                {% for q in authors %}
                <li>
                    {% csrf_token %}
                    <a href=" {% url 'newspaper:detailed' q.id %} "> {{ q.first_name  }} {{ q.last_name }}</a>
                </li>
                </br>
                {% endfor %}
            </ul>

        {% else %}

             <p> No Authors are available. </p>

        {% endif %}

{% endblock %}

newspaper/templates/newspaper/navigation.html
{% load static i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Newspaper</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <div id="topbar">

        <div class="navbar">

             <div class="navbar-content">

                <div class="navbar-nav mr-auto">

                     <a class="navbar" href="{% url 'newspaper:index' %}">
                         <b>Newspaper</b></a>

                     <a class="navbar" href="{% url 'newspaper:add_article' %} ">
                         add Article </a>

                     <a class="navbar" href="{% url 'accounts:login' %}">
                        Login </a>

                     <a class="navbar" href="{% url 'accounts:Signup' %}">
                         Signup </a>

                     <a class="navbar" href=" {% url 'accounts:logout' %}">
                         Logout </a>


                    <form action="{% url 'set_language' %}" method="post" >
                        {% csrf_token %}
                        <input type="hidden" name="text" value="{{ redirect_to }}">
                        <select name="language" id="">
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages%}
                                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE%} selecte {% endif %} >
                                    {{language.name}} ({{ language.code }})

                                </option>
                            {% endfor %}
                        </select>
                        <input type="submit" value="GO">

                    </form>
                    <br>
                </div>

             </div>

        </div>

      </div>

    </div>
</nav>

newspaper/templates/newspaper/widget_employ.html
{% extends "newspaper/base.html" %}
{% load static i18n %}

{% block sub-title %} | Index{% endblock %}

{% block content-main %}

<div>
    <h2> employ the different widgets  </h2>
        <form action="{% url 'newspaper:widget_employ' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>

{% endblock %}