NewspaperManagment/urls.py
from django.contrib import admin
from django.urls import path ,include, re_path
from django.conf import settings
from django.conf.urls.static import static
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('newspaper/', include('newspaper.urls')),
    path('accounts/', include('accounts.urls')),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
    path('blog/', include('blog.urls')),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns = [
    path('search/', views.search, name='search'),
]

tutorial-project/mysite/mysite/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]


urlpatterns += i18n_patterns(path("admin/", admin.site.urls), path("", include("cms.urls")))

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from wagtail.core import blocks
from wagtail.search import index
from modelcluster.fields import ParentalKey
from wagtail.core.fields import StreamField
from wagtail.core.fields import RichTextField
from wagtail.core.models import Page, Orderable
from wagtail.images.blocks import ImageChooserBlock
from wagtail.snippets.models import register_snippet
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel, InlinePanel, StreamFieldPanel


class BlogIndexPage(Page):
    intro = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('intro', classname='full'),
    ]

    subpage_types = ['blog.BlogPage', ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(self, request, *args, **kwargs)

        context['blog_entries'] = BlogPage.objects.child_of(self).live()
        return context

    class Meta:
        verbose_name = "blog index page"
        verbose_name_plural = "blog index pages"


class PersonBlock(blocks.StructBlock):
    first_name = blocks.CharBlock()
    surname = blocks.CharBlock()
    photo = ImageChooserBlock(required=False)
    biography = blocks.RichTextBlock()

    class Meta:
        template = 'blog/blocks/person.html'
        icon = 'user'


class BlogPage(Page, index.Indexed):
    brief_description = RichTextField()
    date = models.DateField(" Post date ")
    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='related_links',
    )

    body = StreamField([
        ('heading', blocks.CharBlock(form_classname="full title",
                                     help_text='the title of related blog',
                                     group='Hi')),
        ('paragraph', blocks.RichTextBlock(group='Hi')),
        ('images', ImageChooserBlock()),
        ('domain', blocks.FloatBlock()),

    ], null=True, )

    additional_information = StreamField([
        ('date', blocks.DateTimeBlock()),

        ('blog_number', blocks.RegexBlock(regex='[0-9]{3}[a-d]',
                                          error_messages={
                                              'invalid': "the number of blog is not valid."})),

        ('category', blocks.ChoiceBlock(choices=[('history', 'History'),
                                                 ('tourism', 'Tourism'),
                                                 ('sport', 'Sport'),
                                                 ], icon='list')),

        ('author', PersonBlock()),

    ], null=True)

    content_panels = Page.content_panels + [
        FieldPanel('brief_description'),
        FieldPanel('date'),
        InlinePanel('related_links', label='Related Links'),
        InlinePanel('advert_placements', label='Adverts'),
        StreamFieldPanel('body'),
        StreamFieldPanel('additional_information'),
    ]

    search_fields = Page.search_fields + [
        index.SearchField('body'),
        index.FilterField('date')
    ]

    promote_panels = [
        MultiFieldPanel(Page.promote_panels, "Common page configuration"),
        ImageChooserPanel('feed_image'),
    ]

    parent_page_types = ['blog.BlogIndexPage', ]
    subpage_types = []


class BlogPageRelatedLink(Orderable):
    blog_page = ParentalKey(BlogPage, on_delete=models.CASCADE, related_name='related_links')
    name = models.CharField(max_length=200)
    url = models.URLField()

    panels = [
        FieldPanel('name'),
        FieldPanel('url'),
    ]


@register_snippet
class Advert(index.Indexed, models.Model):
    text = models.CharField(max_length=200)
    url = models.URLField(null=True, blank=True)

    panels = [
        FieldPanel('text'),
        FieldPanel('url'),
    ]

    search_fields = [
        index.SearchField('text', partial_match=True)
    ]

    def __str__(self):
        return self.text


class BlogPageAdvertPlacement(Orderable, models.Model):
    page = ParentalKey(BlogPage, on_delete=models.CASCADE, related_name='advert_placements')
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE, related_name='+')

    class Meta(Orderable.Meta):
        verbose_name = 'advert placement'
        verbose_name_plural = 'advert placements'

    panels = [
        SnippetChooserPanel('advert')
    ]

    def __str__(self):
        return self.page.title + " -> " + self.advert.text

blog/views.py
from django.shortcuts import render
from wagtail.core.models import Page
from wagtail.search.models import Query


# Create your views here.
def search(request):
    search_query = request.GET.get('query', None)
    if search_query:
        search_results = Page.objects.live().search(search_query)
        Query.get(search_query).add_hit()
    else:
        search_results = Page.objects.none()

    return render(request, 'blog/search_results.html', {
        'search_query': search_query,
        'search_results': search_results
    })

blog/templates/blog/base.html
{% load static i18n %}

<html>

<head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous">
<link href="blog/my_style.css">

</head>

{% block navbar %}
    {% include "blog/navigation.html" %}
{% endblock %}

{% block content %}
    {% block content-main %}
    {% endblock %}
{% endblock %}

</html>

blog/templates/blog/blog_index_page.html
{% extends "blog/base.html" %}

{% load i18n %}
{% load wagtailcore_tags %}
{% load demo_tags %}


{% block body_class %} template-blogpage {% endblock %}

{% block content %}

    {% trans "Let's translate this" %}
        <h1 style="color:#45DF45">
            {{page.title}}
        </h1>

        <div style="color:green">
            {{ page.intro|richtext }}
        </div>

        {%for blog in blog_entries %}
            <h3> {{ blog.title }} </h3>
            {{blog.specific.date}}
            <br>
            <p> ** ----------------------------------------------------------- ** </p>
            <br>
        {% endfor %}

         {% adverts %}

{% endblock %}

blog/templates/blog/blog_page.html
{% extends "blog/base.html" %}

{% load i18n %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}
{% load wagtailuserbar %}
{% load demo_tags %}


{% block body_class %}template-blogpage{% endblock %}

{% block content %}

    {{page.title}}
    <div style="border-color: deeppink;border-style: solid">
        {%include_block page.body%}
    </div>
    <p>
        {{page.date}}
    </p>

    {% wagtailuserbar 'top-right' %}


    {% image page.feed_image width-550 format-webp as webp_image %}
    {% image page.feed_image width-550 format-jpeg as jpeg_image %}

    <div style="border-color: coral; border-style: solid; background: darksalmon">
        {% for block in page.additional_information %}
            {% if block.block_type == 'category' %}
                <p style="font-size: large; color: azure ">
                    The category of blog is : {{ block.value }}
                </p>
                <br>
            {% endif %}

            {% if block.block_type == 'blog_number'%}
                <p style="font-size: large; color: azure ">
                    The number of blog is : {{ block.value }}
                </p>
                <br>
            {% endif %}

            {% if block.block_type == 'date'%}
                <p style="font-size: medium; color: black ">
                   {{ block.value }}
                </p>
                <br>
            {% endif %}
            {% if block.block_type == 'author'%}
                <p style="font-size: large; color: azure ">
                    <h2> Author information </h2>
                   {% include_block block %}
                </p>
                <br>
            {% endif %}

        {% endfor %}
    </div>

     <div style="background-color:darkturquoise">

         <h3 style="color: aliceblue">
              ADVERTS :
         </h3>

         {% for advert_placement in page.advert_placements.all %}
             <p>
                 <a style="color: azure" href="advert_placement.advert.url">
                     {{advert_placement.advert.text}}
                 </a>
             </p>
         {% endfor %}
     </div>
{% endblock %}

blog/templates/blog/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#" style="bold"> Blog </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <div id="topbar">

        <div class="navbar">

             <div class="navbar-content">

                <div class="navbar-nav mr-auto">

                     <a class="navbar" href="">
                         <b> </b></a>

                     <a class="navbar" href=" ">
                          </a>

                     <a class="navbar" href="">
                        Login </a>

                     <a class="navbar" href="">
                         Signup </a>

                     <a class="navbar" href="">
                         Logout </a>
                    <br>
                </div>

             </div>

        </div>

      </div>

    </div>
</nav>

blog/templates/blog/search_results.html
{% extends "blog/base.html" %}

{% load i18n %}
{% load wagtailcore_tags %}


{% block title %} search {% endblock %}

{% block content %}
    <form action="{% url 'blog:search' %}" method="get">
        <input type="text" name="query" value="{{ search_query }}">
        <input type="submit" value="Search">
    </form>

    {% if search_results %}
        <ul>
            {% for result in search_results %}
                <li>
                    <h4><a href="{% pageurl result %}" > {{ result }}  </a></h4>
                    {% if result.search_description %}
                        {{ result.search_description|safe }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% elif search_query %}
        No results found
    {% else %}
        Please type something into the search box
    {% endif%}

{% endblock %}